name: Generate Blog Post

on:
  schedule:
    - cron: '*/60 * * * *'  # Run every 60 minutes
  workflow_dispatch:  # Allow manual triggering

jobs:
  generate-blog-post:
    runs-on: ubuntu-latest
    env:
      GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.PAT }}
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install groq colorama scikit-learn
    - name: Generate blog post
      run: |
        echo "GROQ_API_KEY is set: ${{ env.GROQ_API_KEY != '' }}"
        python main.py
    - name: Commit and push changes
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git fetch origin master
        git reset --hard origin/master
        python main.py
        git add -A
        git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-generated blog post" && git push origin master)
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}